/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
import type * as ownedUpgradeableProxySol from "./OwnedUpgradeableProxy.sol";
export type { ownedUpgradeableProxySol };
import type * as relayer from "./Relayer";
export type { relayer };
import type * as finayNftSol from "./finayNFT.sol";
export type { finayNftSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
