/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC2981Upgradeable__factory } from "./IERC2981Upgradeable__factory";
export { IERC5267Upgradeable__factory } from "./IERC5267Upgradeable__factory";
