/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFinayNFT,
  IFinayNFTInterface,
} from "../../../contracts/interfaces/IFinayNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        internalType: "address",
        name: "_buyer",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "_royaltyfee",
        type: "uint96",
      },
      {
        internalType: "string",
        name: "_tokenuri",
        type: "string",
      },
    ],
    name: "lazyMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFinayNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IFinayNFTInterface {
    return new utils.Interface(_abi) as IFinayNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFinayNFT {
    return new Contract(address, _abi, signerOrProvider) as IFinayNFT;
  }
}
